version: "3.0"

services:
  backend:
    image: debian:bullseye-slim
    environment:
      ENVIRONMENT: dev
    entrypoint: /code/entrypoint.sh
    ports:
      - "80:5000"
    volumes:
      - .:/code
    networks:
      - net

  database:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: DustyDollar
      MYSQL_USER: sherrif
      MYSQL_PASSWORD: maverick
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - net

volumes:
  mysql_db:

networks:
  net: