version: "3.0"

services:
  backend:
    build:
      context: .
    image: dustydollar:latest
    command: sleep 100000
    env_file:
      - .env.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    networks:
      - net

  database:
    image: mysql:8.0-debian
    env_file:
      - .env.dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - net

volumes:
  mysql_db:

networks:
  net: