"""empty message

Revision ID: 06cfca3a99b4
Revises: 39e731e15a00
Create Date: 2023-12-21 16:22:12.037310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06cfca3a99b4'
down_revision = '39e731e15a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.drop_column('teste')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teste', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
