"""empty message

Revision ID: 15c92bbf4926
Revises: a53a291aee49
Create Date: 2023-12-18 11:34:20.862732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15c92bbf4926'
down_revision = 'a53a291aee49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.alter_column('id_pessoa',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('tipo_conta',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('data_criacao',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.alter_column('id_conta',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('valor',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)
        batch_op.alter_column('data_transacao',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.alter_column('data_transacao',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('valor',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
        batch_op.alter_column('id_conta',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('tipo_conta',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
        batch_op.alter_column('id_pessoa',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
