"""empty message

Revision ID: a53a291aee49
Revises: 
Create Date: 2023-12-15 03:35:55.800377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53a291aee49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta',
    sa.Column('id_conta', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=True),
    sa.Column('saldo', sa.Numeric(), nullable=True),
    sa.Column('limite_saque_diario', sa.Numeric(), nullable=True),
    sa.Column('flag_ativo', sa.Boolean(), nullable=True),
    sa.Column('tipo_conta', sa.Numeric(), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_conta')
    )
    op.create_table('pessoa',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_pessoa')
    )
    op.create_table('transacao',
    sa.Column('id_transacao', sa.Integer(), nullable=False),
    sa.Column('id_conta', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(), nullable=True),
    sa.Column('data_transacao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_transacao')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    op.drop_table('pessoa')
    op.drop_table('conta')
    # ### end Alembic commands ###
